package SDL::Events;
use strict;
use warnings;
require Exporter;
require DynaLoader;
our @ISA = qw(Exporter DynaLoader);

use SDL::Internal::Loader;
internal_load_dlls(__PACKAGE__);

bootstrap SDL::Events;

use base 'Exporter';

our @EXPORT = qw(
	SDL_ACTIVEEVENT
	SDL_KEYDOWN
	SDL_KEYUP
	SDL_MOUSEMOTION
	SDL_MOUSEBUTTONDOWN
	SDL_MOUSEBUTTONUP
	SDL_JOYAXISMOTION
	SDL_JOYBALLMOTION
	SDL_JOYHATMOTION
	SDL_JOYBUTTONDOWN
	SDL_JOYBUTTONUP
	SDL_QUIT
	SDL_SYSWMEVENT
	SDL_VIDEORESIZE
	SDL_VIDEOEXPOSE
	SDL_USEREVENT
	SDL_NUMEVENTS
	SDL_EVENTMASK
	SDL_ACTIVEEVENTMASK
	SDL_KEYDOWNMASK
	SDL_KEYUPMASK
	SDL_KEYEVENTMASK
	SDL_MOUSEMOTIONMASK
	SDL_MOUSEBUTTONDOWNMASK
	SDL_MOUSEBUTTONUPMASK
	SDL_MOUSEEVENTMASK
	SDL_JOYAXISMOTIONMASK
	SDL_JOYBALLMOTIONMASK
	SDL_JOYHATMOTIONMASK
	SDL_JOYBUTTONDOWNMASK
	SDL_JOYBUTTONUPMASK
	SDL_JOYEVENTMASK
	SDL_VIDEORESIZEMASK
	SDL_VIDEOEXPOSEMASK
	SDL_QUITMASK
	SDL_SYSWMEVENTMASK
	SDL_ALLEVENTS
	SDL_ADDEVENT
	SDL_PEEKEVENT
	SDL_GETEVENT
	SDL_QUERY
	SDL_IGNORE
	SDL_DISABLE
	SDL_ENABLE
	SDL_RELEASED
	SDL_PRESSED
	SDL_HAT_CENTERED
	SDL_HAT_UP
	SDL_HAT_RIGHT
	SDL_HAT_DOWN
	SDL_HAT_LEFT
	SDL_HAT_RIGHTUP
	SDL_HAT_RIGHTDOWN
	SDL_HAT_LEFTUP
	SDL_HAT_LEFTDOWN
	SDL_APPMOUSEFOCUS
	SDL_APPINPUTFOCUS
	SDL_APPACTIVE
	SDL_BUTTON
	SDL_BUTTON_LEFT
	SDL_BUTTON_MIDDLE
	SDL_BUTTON_RIGHT
	SDL_BUTTON_WHEELUP
	SDL_BUTTON_WHEELDOWN
	SDL_BUTTON_X1
	SDL_BUTTON_X2
	SDL_BUTTON_LMASK
	SDL_BUTTON_MMASK
	SDL_BUTTON_RMASK
	SDL_BUTTON_X1MASK
	SDL_BUTTON_X2MASK
	SDLK_UNKNOWN
	SDLK_FIRST
	SDLK_BACKSPACE
	SDLK_TAB
	SDLK_CLEAR
	SDLK_RETURN
	SDLK_PAUSE
	SDLK_ESCAPE
	SDLK_SPACE
	SDLK_EXCLAIM
	SDLK_QUOTEDBL
	SDLK_HASH
	SDLK_DOLLAR
	SDLK_AMPERSAND
	SDLK_QUOTE
	SDLK_LEFTPAREN
	SDLK_RIGHTPAREN
	SDLK_ASTERISK
	SDLK_PLUS
	SDLK_COMMA
	SDLK_MINUS
	SDLK_PERIOD
	SDLK_SLASH
	SDLK_0
	SDLK_1
	SDLK_2
	SDLK_3
	SDLK_4
	SDLK_5
	SDLK_6
	SDLK_7
	SDLK_8
	SDLK_9
	SDLK_COLON
	SDLK_SEMICOLON
	SDLK_LESS
	SDLK_EQUALS
	SDLK_GREATER
	SDLK_QUESTION
	SDLK_AT
	SDLK_LEFTBRACKET
	SDLK_BACKSLASH
	SDLK_RIGHTBRACKET
	SDLK_CARET
	SDLK_UNDERSCORE
	SDLK_BACKQUOTE
	SDLK_a
	SDLK_b
	SDLK_c
	SDLK_d
	SDLK_e
	SDLK_f
	SDLK_g
	SDLK_h
	SDLK_i
	SDLK_j
	SDLK_k
	SDLK_l
	SDLK_m
	SDLK_n
	SDLK_o
	SDLK_p
	SDLK_q
	SDLK_r
	SDLK_s
	SDLK_t
	SDLK_u
	SDLK_v
	SDLK_w
	SDLK_x
	SDLK_y
	SDLK_z
	SDLK_DELETE
	SDLK_WORLD_0
	SDLK_WORLD_1
	SDLK_WORLD_2
	SDLK_WORLD_3
	SDLK_WORLD_4
	SDLK_WORLD_5
	SDLK_WORLD_6
	SDLK_WORLD_7
	SDLK_WORLD_8
	SDLK_WORLD_9
	SDLK_WORLD_10
	SDLK_WORLD_11
	SDLK_WORLD_12
	SDLK_WORLD_13
	SDLK_WORLD_14
	SDLK_WORLD_15
	SDLK_WORLD_16
	SDLK_WORLD_17
	SDLK_WORLD_18
	SDLK_WORLD_19
	SDLK_WORLD_20
	SDLK_WORLD_21
	SDLK_WORLD_22
	SDLK_WORLD_23
	SDLK_WORLD_24
	SDLK_WORLD_25
	SDLK_WORLD_26
	SDLK_WORLD_27
	SDLK_WORLD_28
	SDLK_WORLD_29
	SDLK_WORLD_30
	SDLK_WORLD_31
	SDLK_WORLD_32
	SDLK_WORLD_33
	SDLK_WORLD_34
	SDLK_WORLD_35
	SDLK_WORLD_36
	SDLK_WORLD_37
	SDLK_WORLD_38
	SDLK_WORLD_39
	SDLK_WORLD_40
	SDLK_WORLD_41
	SDLK_WORLD_42
	SDLK_WORLD_43
	SDLK_WORLD_44
	SDLK_WORLD_45
	SDLK_WORLD_46
	SDLK_WORLD_47
	SDLK_WORLD_48
	SDLK_WORLD_49
	SDLK_WORLD_50
	SDLK_WORLD_51
	SDLK_WORLD_52
	SDLK_WORLD_53
	SDLK_WORLD_54
	SDLK_WORLD_55
	SDLK_WORLD_56
	SDLK_WORLD_57
	SDLK_WORLD_58
	SDLK_WORLD_59
	SDLK_WORLD_60
	SDLK_WORLD_61
	SDLK_WORLD_62
	SDLK_WORLD_63
	SDLK_WORLD_64
	SDLK_WORLD_65
	SDLK_WORLD_66
	SDLK_WORLD_67
	SDLK_WORLD_68
	SDLK_WORLD_69
	SDLK_WORLD_70
	SDLK_WORLD_71
	SDLK_WORLD_72
	SDLK_WORLD_73
	SDLK_WORLD_74
	SDLK_WORLD_75
	SDLK_WORLD_76
	SDLK_WORLD_77
	SDLK_WORLD_78
	SDLK_WORLD_79
	SDLK_WORLD_80
	SDLK_WORLD_81
	SDLK_WORLD_82
	SDLK_WORLD_83
	SDLK_WORLD_84
	SDLK_WORLD_85
	SDLK_WORLD_86
	SDLK_WORLD_87
	SDLK_WORLD_88
	SDLK_WORLD_89
	SDLK_WORLD_90
	SDLK_WORLD_91
	SDLK_WORLD_92
	SDLK_WORLD_93
	SDLK_WORLD_94
	SDLK_WORLD_95
	SDLK_KP0
	SDLK_KP1
	SDLK_KP2
	SDLK_KP3
	SDLK_KP4
	SDLK_KP5
	SDLK_KP6
	SDLK_KP7
	SDLK_KP8
	SDLK_KP9
	SDLK_KP_PERIOD
	SDLK_KP_DIVIDE
	SDLK_KP_MULTIPLY
	SDLK_KP_MINUS
	SDLK_KP_PLUS
	SDLK_KP_ENTER
	SDLK_KP_EQUALS
	SDLK_UP
	SDLK_DOWN
	SDLK_RIGHT
	SDLK_LEFT
	SDLK_INSERT
	SDLK_HOME
	SDLK_END
	SDLK_PAGEUP
	SDLK_PAGEDOWN
	SDLK_F1
	SDLK_F2
	SDLK_F3
	SDLK_F4
	SDLK_F5
	SDLK_F6
	SDLK_F7
	SDLK_F8
	SDLK_F9
	SDLK_F10
	SDLK_F11
	SDLK_F12
	SDLK_F13
	SDLK_F14
	SDLK_F15
	SDLK_NUMLOCK
	SDLK_CAPSLOCK
	SDLK_SCROLLOCK
	SDLK_RSHIFT
	SDLK_LSHIFT
	SDLK_RCTRL
	SDLK_LCTRL
	SDLK_RALT
	SDLK_LALT
	SDLK_RMETA
	SDLK_LMETA
	SDLK_LSUPER
	SDLK_RSUPER
	SDLK_MODE
	SDLK_COMPOSE
	SDLK_HELP
	SDLK_PRINT
	SDLK_SYSREQ
	SDLK_BREAK
	SDLK_MENU
	SDLK_POWER
	SDLK_EURO
	SDLK_UNDO
	KMOD_NONE
	KMOD_LSHIFT
	KMOD_RSHIFT
	KMOD_LCTRL
	KMOD_RCTRL
	KMOD_LALT
	KMOD_RALT
	KMOD_LMETA
	KMOD_RMETA
	KMOD_NUM
	KMOD_CAPS
	KMOD_MODE
	KMOD_RESERVED
	KMOD_CTRL
	KMOD_SHIFT
	KMOD_ALT
	KMOD_META
);

our %EXPORT_TAGS = 
(
	type => [qw(
		SDL_ACTIVEEVENT
		SDL_KEYDOWN
		SDL_KEYUP
		SDL_MOUSEMOTION
		SDL_MOUSEBUTTONDOWN
		SDL_MOUSEBUTTONUP
		SDL_JOYAXISMOTION
		SDL_JOYBALLMOTION
		SDL_JOYHATMOTION
		SDL_JOYBUTTONDOWN
		SDL_JOYBUTTONUP
		SDL_QUIT
		SDL_SYSWMEVENT
		SDL_VIDEORESIZE
		SDL_VIDEOEXPOSE
		SDL_USEREVENT
		SDL_NUMEVENTS
	)],
	mask => [qw(
		SDL_EVENTMASK
		SDL_ACTIVEEVENTMASK
		SDL_KEYDOWNMASK
		SDL_KEYUPMASK
		SDL_KEYEVENTMASK
		SDL_MOUSEMOTIONMASK
		SDL_MOUSEBUTTONDOWNMASK
		SDL_MOUSEBUTTONUPMASK
		SDL_MOUSEEVENTMASK
		SDL_JOYAXISMOTIONMASK
		SDL_JOYBALLMOTIONMASK
		SDL_JOYHATMOTIONMASK
		SDL_JOYBUTTONDOWNMASK
		SDL_JOYBUTTONUPMASK
		SDL_JOYEVENTMASK
		SDL_VIDEORESIZEMASK
		SDL_VIDEOEXPOSEMASK
		SDL_QUITMASK
		SDL_SYSWMEVENTMASK
		SDL_ALLEVENTS
	)],
	action => [qw(
		SDL_ADDEVENT
		SDL_PEEKEVENT
		SDL_GETEVENT
	)],
	state => [qw(
		SDL_QUERY
		SDL_IGNORE
		SDL_DISABLE
		SDL_ENABLE
		SDL_RELEASED
		SDL_PRESSED
	)],
	hat => [qw(
		SDL_HAT_CENTERED
		SDL_HAT_UP
		SDL_HAT_RIGHT
		SDL_HAT_DOWN
		SDL_HAT_LEFT
		SDL_HAT_RIGHTUP
		SDL_HAT_RIGHTDOWN
		SDL_HAT_LEFTUP
		SDL_HAT_LEFTDOWN
	)],
	app => [qw(
		SDL_APPMOUSEFOCUS
		SDL_APPINPUTFOCUS
		SDL_APPACTIVE
	)],
	button => [qw(
		SDL_BUTTON
		SDL_BUTTON_LEFT
		SDL_BUTTON_MIDDLE
		SDL_BUTTON_RIGHT
		SDL_BUTTON_WHEELUP
		SDL_BUTTON_WHEELDOWN
		SDL_BUTTON_X1
		SDL_BUTTON_X2
		SDL_BUTTON_LMASK
		SDL_BUTTON_MMASK
		SDL_BUTTON_RMASK
		SDL_BUTTON_X1MASK
		SDL_BUTTON_X2MASK
	)],
	keysym  => [qw(
		SDLK_UNKNOWN
		SDLK_FIRST
		SDLK_BACKSPACE
		SDLK_TAB
		SDLK_CLEAR
		SDLK_RETURN
		SDLK_PAUSE
		SDLK_ESCAPE
		SDLK_SPACE
		SDLK_EXCLAIM
		SDLK_QUOTEDBL
		SDLK_HASH
		SDLK_DOLLAR
		SDLK_AMPERSAND
		SDLK_QUOTE
		SDLK_LEFTPAREN
		SDLK_RIGHTPAREN
		SDLK_ASTERISK
		SDLK_PLUS
		SDLK_COMMA
		SDLK_MINUS
		SDLK_PERIOD
		SDLK_SLASH
		SDLK_0
		SDLK_1
		SDLK_2
		SDLK_3
		SDLK_4
		SDLK_5
		SDLK_6
		SDLK_7
		SDLK_8
		SDLK_9
		SDLK_COLON
		SDLK_SEMICOLON
		SDLK_LESS
		SDLK_EQUALS
		SDLK_GREATER
		SDLK_QUESTION
		SDLK_AT
		SDLK_LEFTBRACKET
		SDLK_BACKSLASH
		SDLK_RIGHTBRACKET
		SDLK_CARET
		SDLK_UNDERSCORE
		SDLK_BACKQUOTE
		SDLK_a
		SDLK_b
		SDLK_c
		SDLK_d
		SDLK_e
		SDLK_f
		SDLK_g
		SDLK_h
		SDLK_i
		SDLK_j
		SDLK_k
		SDLK_l
		SDLK_m
		SDLK_n
		SDLK_o
		SDLK_p
		SDLK_q
		SDLK_r
		SDLK_s
		SDLK_t
		SDLK_u
		SDLK_v
		SDLK_w
		SDLK_x
		SDLK_y
		SDLK_z
		SDLK_DELETE
		SDLK_WORLD_0
		SDLK_WORLD_1
		SDLK_WORLD_2
		SDLK_WORLD_3
		SDLK_WORLD_4
		SDLK_WORLD_5
		SDLK_WORLD_6
		SDLK_WORLD_7
		SDLK_WORLD_8
		SDLK_WORLD_9
		SDLK_WORLD_10
		SDLK_WORLD_11
		SDLK_WORLD_12
		SDLK_WORLD_13
		SDLK_WORLD_14
		SDLK_WORLD_15
		SDLK_WORLD_16
		SDLK_WORLD_17
		SDLK_WORLD_18
		SDLK_WORLD_19
		SDLK_WORLD_20
		SDLK_WORLD_21
		SDLK_WORLD_22
		SDLK_WORLD_23
		SDLK_WORLD_24
		SDLK_WORLD_25
		SDLK_WORLD_26
		SDLK_WORLD_27
		SDLK_WORLD_28
		SDLK_WORLD_29
		SDLK_WORLD_30
		SDLK_WORLD_31
		SDLK_WORLD_32
		SDLK_WORLD_33
		SDLK_WORLD_34
		SDLK_WORLD_35
		SDLK_WORLD_36
		SDLK_WORLD_37
		SDLK_WORLD_38
		SDLK_WORLD_39
		SDLK_WORLD_40
		SDLK_WORLD_41
		SDLK_WORLD_42
		SDLK_WORLD_43
		SDLK_WORLD_44
		SDLK_WORLD_45
		SDLK_WORLD_46
		SDLK_WORLD_47
		SDLK_WORLD_48
		SDLK_WORLD_49
		SDLK_WORLD_50
		SDLK_WORLD_51
		SDLK_WORLD_52
		SDLK_WORLD_53
		SDLK_WORLD_54
		SDLK_WORLD_55
		SDLK_WORLD_56
		SDLK_WORLD_57
		SDLK_WORLD_58
		SDLK_WORLD_59
		SDLK_WORLD_60
		SDLK_WORLD_61
		SDLK_WORLD_62
		SDLK_WORLD_63
		SDLK_WORLD_64
		SDLK_WORLD_65
		SDLK_WORLD_66
		SDLK_WORLD_67
		SDLK_WORLD_68
		SDLK_WORLD_69
		SDLK_WORLD_70
		SDLK_WORLD_71
		SDLK_WORLD_72
		SDLK_WORLD_73
		SDLK_WORLD_74
		SDLK_WORLD_75
		SDLK_WORLD_76
		SDLK_WORLD_77
		SDLK_WORLD_78
		SDLK_WORLD_79
		SDLK_WORLD_80
		SDLK_WORLD_81
		SDLK_WORLD_82
		SDLK_WORLD_83
		SDLK_WORLD_84
		SDLK_WORLD_85
		SDLK_WORLD_86
		SDLK_WORLD_87
		SDLK_WORLD_88
		SDLK_WORLD_89
		SDLK_WORLD_90
		SDLK_WORLD_91
		SDLK_WORLD_92
		SDLK_WORLD_93
		SDLK_WORLD_94
		SDLK_WORLD_95
		SDLK_KP0
		SDLK_KP1
		SDLK_KP2
		SDLK_KP3
		SDLK_KP4
		SDLK_KP5
		SDLK_KP6
		SDLK_KP7
		SDLK_KP8
		SDLK_KP9
		SDLK_KP_PERIOD
		SDLK_KP_DIVIDE
		SDLK_KP_MULTIPLY
		SDLK_KP_MINUS
		SDLK_KP_PLUS
		SDLK_KP_ENTER
		SDLK_KP_EQUALS
		SDLK_UP
		SDLK_DOWN
		SDLK_RIGHT
		SDLK_LEFT
		SDLK_INSERT
		SDLK_HOME
		SDLK_END
		SDLK_PAGEUP
		SDLK_PAGEDOWN
		SDLK_F1
		SDLK_F2
		SDLK_F3
		SDLK_F4
		SDLK_F5
		SDLK_F6
		SDLK_F7
		SDLK_F8
		SDLK_F9
		SDLK_F10
		SDLK_F11
		SDLK_F12
		SDLK_F13
		SDLK_F14
		SDLK_F15
		SDLK_NUMLOCK
		SDLK_CAPSLOCK
		SDLK_SCROLLOCK
		SDLK_RSHIFT
		SDLK_LSHIFT
		SDLK_RCTRL
		SDLK_LCTRL
		SDLK_RALT
		SDLK_LALT
		SDLK_RMETA
		SDLK_LMETA
		SDLK_LSUPER
		SDLK_RSUPER
		SDLK_MODE
		SDLK_COMPOSE
		SDLK_HELP
		SDLK_PRINT
		SDLK_SYSREQ
		SDLK_BREAK
		SDLK_MENU
		SDLK_POWER
		SDLK_EURO
		SDLK_UNDO
	)],
	keymod => [qw(
		KMOD_NONE
		KMOD_LSHIFT
		KMOD_RSHIFT
		KMOD_LCTRL
		KMOD_RCTRL
		KMOD_LALT
		KMOD_RALT
		KMOD_LMETA
		KMOD_RMETA
		KMOD_NUM
		KMOD_CAPS
		KMOD_MODE
		KMOD_RESERVED
		KMOD_CTRL
		KMOD_SHIFT
		KMOD_ALT
		KMOD_META
	)],
);

use constant{
	SDL_ACTIVEEVENT     => 1,
	SDL_KEYDOWN         => 2,
	SDL_KEYUP           => 3,
	SDL_MOUSEMOTION     => 4,
	SDL_MOUSEBUTTONDOWN => 5,
	SDL_MOUSEBUTTONUP   => 6,
	SDL_JOYAXISMOTION   => 7,
	SDL_JOYBALLMOTION   => 8,
	SDL_JOYHATMOTION    => 9,
	SDL_JOYBUTTONDOWN   => 10,
	SDL_JOYBUTTONUP     => 11,
	SDL_QUIT            => 12,
	SDL_SYSWMEVENT      => 13,
	SDL_VIDEORESIZE     => 16,
	SDL_VIDEOEXPOSE     => 17,
	SDL_USEREVENT       => 24,
	SDL_NUMEVENTS       => 32,
}; # type

sub SDL_EVENTMASK{ return 1 << shift; }

use constant{
	SDL_ACTIVEEVENTMASK     => SDL_EVENTMASK(SDL_ACTIVEEVENT),
	SDL_KEYDOWNMASK         => SDL_EVENTMASK(SDL_KEYDOWN),
	SDL_KEYUPMASK           => SDL_EVENTMASK(SDL_KEYUP),
	SDL_KEYEVENTMASK        => SDL_EVENTMASK(SDL_KEYDOWN)
	                         | SDL_EVENTMASK(SDL_KEYUP),
	SDL_MOUSEMOTIONMASK     => SDL_EVENTMASK(SDL_MOUSEMOTION),
	SDL_MOUSEBUTTONDOWNMASK => SDL_EVENTMASK(SDL_MOUSEBUTTONDOWN),
	SDL_MOUSEBUTTONUPMASK   => SDL_EVENTMASK(SDL_MOUSEBUTTONUP),
	SDL_MOUSEEVENTMASK      => SDL_EVENTMASK(SDL_MOUSEMOTION)
	                         | SDL_EVENTMASK(SDL_MOUSEBUTTONDOWN)
							 | SDL_EVENTMASK(SDL_MOUSEBUTTONUP),
	SDL_JOYAXISMOTIONMASK   => SDL_EVENTMASK(SDL_JOYAXISMOTION),
	SDL_JOYBALLMOTIONMASK   => SDL_EVENTMASK(SDL_JOYBALLMOTION),
	SDL_JOYHATMOTIONMASK    => SDL_EVENTMASK(SDL_JOYHATMOTION),
	SDL_JOYBUTTONDOWNMASK   => SDL_EVENTMASK(SDL_JOYBUTTONDOWN),
	SDL_JOYBUTTONUPMASK     => SDL_EVENTMASK(SDL_JOYBUTTONUP),
	SDL_JOYEVENTMASK        => SDL_EVENTMASK(SDL_JOYAXISMOTION)
	                         | SDL_EVENTMASK(SDL_JOYBALLMOTION)
							 | SDL_EVENTMASK(SDL_JOYHATMOTION)
							 | SDL_EVENTMASK(SDL_JOYBUTTONDOWN)
							 | SDL_EVENTMASK(SDL_JOYBUTTONUP),
	SDL_VIDEORESIZEMASK     => SDL_EVENTMASK(SDL_VIDEORESIZE),
	SDL_VIDEOEXPOSEMASK     => SDL_EVENTMASK(SDL_VIDEOEXPOSE),
	SDL_QUITMASK            => SDL_EVENTMASK(SDL_QUIT),
	SDL_SYSWMEVENTMASK      => SDL_EVENTMASK(SDL_SYSWMEVENT),
	SDL_ALLEVENTS           => 0xFFFFFFFF,
}; # mask

use constant{
	SDL_ADDEVENT  => 0,
	SDL_PEEKEVENT => 1,
	SDL_GETEVENT  => 2,
}; # action

use constant{
	SDL_QUERY    => -1,
	SDL_IGNORE   => 0,
	SDL_DISABLE  => 0,
	SDL_ENABLE   => 1,
	SDL_RELEASED => 0,
	SDL_PRESSED  => 1,
}; # state

use constant{
	SDL_HAT_CENTERED  => 0x00,
	SDL_HAT_UP        => 0x01,
	SDL_HAT_RIGHT     => 0x02,
	SDL_HAT_DOWN      => 0x04,
	SDL_HAT_LEFT      => 0x08,
	SDL_HAT_RIGHTUP   => (0x02|0x01),
	SDL_HAT_RIGHTDOWN => (0x02|0x04),
	SDL_HAT_LEFTUP    => (0x08|0x01),
	SDL_HAT_LEFTDOWN  => (0x08|0x04),
}; # hat

use constant{
	SDL_APPMOUSEFOCUS => 0x01,
	SDL_APPINPUTFOCUS => 0x02,
	SDL_APPACTIVE     => 0x04,
}; # app

sub SDL_BUTTON{ return	(1 << (($_[0])-1)); }

use constant{
	SDL_BUTTON_LEFT      => 1,
	SDL_BUTTON_MIDDLE    => 2,
	SDL_BUTTON_RIGHT     => 3,
	SDL_BUTTON_WHEELUP   => 4,
	SDL_BUTTON_WHEELDOWN => 5,
	SDL_BUTTON_X1        => 6,
	SDL_BUTTON_X2        => 7,
	SDL_BUTTON_LMASK     => SDL_BUTTON(1),
	SDL_BUTTON_MMASK     => SDL_BUTTON(2),
	SDL_BUTTON_RMASK     => SDL_BUTTON(3),
	SDL_BUTTON_X1MASK    => SDL_BUTTON(6),
	SDL_BUTTON_X2MASK    => SDL_BUTTON(7),
}; # button

use constant{
	SDLK_UNKNOWN		=> 0,
	SDLK_FIRST		=> 0,
	SDLK_BACKSPACE		=> 8,
	SDLK_TAB		=> 9,
	SDLK_CLEAR		=> 12,
	SDLK_RETURN		=> 13,
	SDLK_PAUSE		=> 19,
	SDLK_ESCAPE		=> 27,
	SDLK_SPACE		=> 32,
	SDLK_EXCLAIM		=> 33,
	SDLK_QUOTEDBL		=> 34,
	SDLK_HASH		=> 35,
	SDLK_DOLLAR		=> 36,
	SDLK_AMPERSAND		=> 38,
	SDLK_QUOTE		=> 39,
	SDLK_LEFTPAREN		=> 40,
	SDLK_RIGHTPAREN		=> 41,
	SDLK_ASTERISK		=> 42,
	SDLK_PLUS		=> 43,
	SDLK_COMMA		=> 44,
	SDLK_MINUS		=> 45,
	SDLK_PERIOD		=> 46,
	SDLK_SLASH		=> 47,
	SDLK_0			=> 48,
	SDLK_1			=> 49,
	SDLK_2			=> 50,
	SDLK_3			=> 51,
	SDLK_4			=> 52,
	SDLK_5			=> 53,
	SDLK_6			=> 54,
	SDLK_7			=> 55,
	SDLK_8			=> 56,
	SDLK_9			=> 57,
	SDLK_COLON		=> 58,
	SDLK_SEMICOLON		=> 59,
	SDLK_LESS		=> 60,
	SDLK_EQUALS		=> 61,
	SDLK_GREATER		=> 62,
	SDLK_QUESTION		=> 63,
	SDLK_AT			=> 64,
	SDLK_LEFTBRACKET	=> 91,
	SDLK_BACKSLASH		=> 92,
	SDLK_RIGHTBRACKET	=> 93,
	SDLK_CARET		=> 94,
	SDLK_UNDERSCORE		=> 95,
	SDLK_BACKQUOTE		=> 96,
	SDLK_a			=> 97,
	SDLK_b			=> 98,
	SDLK_c			=> 99,
	SDLK_d			=> 100,
	SDLK_e			=> 101,
	SDLK_f			=> 102,
	SDLK_g			=> 103,
	SDLK_h			=> 104,
	SDLK_i			=> 105,
	SDLK_j			=> 106,
	SDLK_k			=> 107,
	SDLK_l			=> 108,
	SDLK_m			=> 109,
	SDLK_n			=> 110,
	SDLK_o			=> 111,
	SDLK_p			=> 112,
	SDLK_q			=> 113,
	SDLK_r			=> 114,
	SDLK_s			=> 115,
	SDLK_t			=> 116,
	SDLK_u			=> 117,
	SDLK_v			=> 118,
	SDLK_w			=> 119,
	SDLK_x			=> 120,
	SDLK_y			=> 121,
	SDLK_z			=> 122,
	SDLK_DELETE		=> 127,
	SDLK_WORLD_0		=> 160,
	SDLK_WORLD_1		=> 161,
	SDLK_WORLD_2		=> 162,
	SDLK_WORLD_3		=> 163,
	SDLK_WORLD_4		=> 164,
	SDLK_WORLD_5		=> 165,
	SDLK_WORLD_6		=> 166,
	SDLK_WORLD_7		=> 167,
	SDLK_WORLD_8		=> 168,
	SDLK_WORLD_9		=> 169,
	SDLK_WORLD_10		=> 170,
	SDLK_WORLD_11		=> 171,
	SDLK_WORLD_12		=> 172,
	SDLK_WORLD_13		=> 173,
	SDLK_WORLD_14		=> 174,
	SDLK_WORLD_15		=> 175,
	SDLK_WORLD_16		=> 176,
	SDLK_WORLD_17		=> 177,
	SDLK_WORLD_18		=> 178,
	SDLK_WORLD_19		=> 179,
	SDLK_WORLD_20		=> 180,
	SDLK_WORLD_21		=> 181,
	SDLK_WORLD_22		=> 182,
	SDLK_WORLD_23		=> 183,
	SDLK_WORLD_24		=> 184,
	SDLK_WORLD_25		=> 185,
	SDLK_WORLD_26		=> 186,
	SDLK_WORLD_27		=> 187,
	SDLK_WORLD_28		=> 188,
	SDLK_WORLD_29		=> 189,
	SDLK_WORLD_30		=> 190,
	SDLK_WORLD_31		=> 191,
	SDLK_WORLD_32		=> 192,
	SDLK_WORLD_33		=> 193,
	SDLK_WORLD_34		=> 194,
	SDLK_WORLD_35		=> 195,
	SDLK_WORLD_36		=> 196,
	SDLK_WORLD_37		=> 197,
	SDLK_WORLD_38		=> 198,
	SDLK_WORLD_39		=> 199,
	SDLK_WORLD_40		=> 200,
	SDLK_WORLD_41		=> 201,
	SDLK_WORLD_42		=> 202,
	SDLK_WORLD_43		=> 203,
	SDLK_WORLD_44		=> 204,
	SDLK_WORLD_45		=> 205,
	SDLK_WORLD_46		=> 206,
	SDLK_WORLD_47		=> 207,
	SDLK_WORLD_48		=> 208,
	SDLK_WORLD_49		=> 209,
	SDLK_WORLD_50		=> 210,
	SDLK_WORLD_51		=> 211,
	SDLK_WORLD_52		=> 212,
	SDLK_WORLD_53		=> 213,
	SDLK_WORLD_54		=> 214,
	SDLK_WORLD_55		=> 215,
	SDLK_WORLD_56		=> 216,
	SDLK_WORLD_57		=> 217,
	SDLK_WORLD_58		=> 218,
	SDLK_WORLD_59		=> 219,
	SDLK_WORLD_60		=> 220,
	SDLK_WORLD_61		=> 221,
	SDLK_WORLD_62		=> 222,
	SDLK_WORLD_63		=> 223,
	SDLK_WORLD_64		=> 224,
	SDLK_WORLD_65		=> 225,
	SDLK_WORLD_66		=> 226,
	SDLK_WORLD_67		=> 227,
	SDLK_WORLD_68		=> 228,
	SDLK_WORLD_69		=> 229,
	SDLK_WORLD_70		=> 230,
	SDLK_WORLD_71		=> 231,
	SDLK_WORLD_72		=> 232,
	SDLK_WORLD_73		=> 233,
	SDLK_WORLD_74		=> 234,
	SDLK_WORLD_75		=> 235,
	SDLK_WORLD_76		=> 236,
	SDLK_WORLD_77		=> 237,
	SDLK_WORLD_78		=> 238,
	SDLK_WORLD_79		=> 239,
	SDLK_WORLD_80		=> 240,
	SDLK_WORLD_81		=> 241,
	SDLK_WORLD_82		=> 242,
	SDLK_WORLD_83		=> 243,
	SDLK_WORLD_84		=> 244,
	SDLK_WORLD_85		=> 245,
	SDLK_WORLD_86		=> 246,
	SDLK_WORLD_87		=> 247,
	SDLK_WORLD_88		=> 248,
	SDLK_WORLD_89		=> 249,
	SDLK_WORLD_90		=> 250,
	SDLK_WORLD_91		=> 251,
	SDLK_WORLD_92		=> 252,
	SDLK_WORLD_93		=> 253,
	SDLK_WORLD_94		=> 254,
	SDLK_WORLD_95		=> 255,	
	SDLK_KP0		=> 256,
	SDLK_KP1		=> 257,
	SDLK_KP2		=> 258,
	SDLK_KP3		=> 259,
	SDLK_KP4		=> 260,
	SDLK_KP5		=> 261,
	SDLK_KP6		=> 262,
	SDLK_KP7		=> 263,
	SDLK_KP8		=> 264,
	SDLK_KP9		=> 265,
	SDLK_KP_PERIOD		=> 266,
	SDLK_KP_DIVIDE		=> 267,
	SDLK_KP_MULTIPLY	=> 268,
	SDLK_KP_MINUS		=> 269,
	SDLK_KP_PLUS		=> 270,
	SDLK_KP_ENTER		=> 271,
	SDLK_KP_EQUALS		=> 272,
	SDLK_UP			=> 273,
	SDLK_DOWN		=> 274,
	SDLK_RIGHT		=> 275,
	SDLK_LEFT		=> 276,
	SDLK_INSERT		=> 277,
	SDLK_HOME		=> 278,
	SDLK_END		=> 279,
	SDLK_PAGEUP		=> 280,
	SDLK_PAGEDOWN		=> 281,
	SDLK_F1			=> 282,
	SDLK_F2			=> 283,
	SDLK_F3			=> 284,
	SDLK_F4			=> 285,
	SDLK_F5			=> 286,
	SDLK_F6			=> 287,
	SDLK_F7			=> 288,
	SDLK_F8			=> 289,
	SDLK_F9			=> 290,
	SDLK_F10		=> 291,
	SDLK_F11		=> 292,
	SDLK_F12		=> 293,
	SDLK_F13		=> 294,
	SDLK_F14		=> 295,
	SDLK_F15		=> 296,
	SDLK_NUMLOCK		=> 300,
	SDLK_CAPSLOCK		=> 301,
	SDLK_SCROLLOCK		=> 302,
	SDLK_RSHIFT		=> 303,
	SDLK_LSHIFT		=> 304,
	SDLK_RCTRL		=> 305,
	SDLK_LCTRL		=> 306,
	SDLK_RALT		=> 307,
	SDLK_LALT		=> 308,
	SDLK_RMETA		=> 309,
	SDLK_LMETA		=> 310,
	SDLK_LSUPER		=> 311,
	SDLK_RSUPER		=> 312,
	SDLK_MODE		=> 313,
	SDLK_COMPOSE		=> 314,
	SDLK_HELP		=> 315,
	SDLK_PRINT		=> 316,
	SDLK_SYSREQ		=> 317,
	SDLK_BREAK		=> 318,
	SDLK_MENU		=> 319,
	SDLK_POWER		=> 320,
	SDLK_EURO		=> 321,
	SDLK_UNDO		=> 322,
}; # keysym

use constant{
	KMOD_NONE     => 0x0000,
	KMOD_LSHIFT   => 0x0001,
	KMOD_RSHIFT   => 0x0002,
	KMOD_LCTRL    => 0x0040,
	KMOD_RCTRL    => 0x0080,
	KMOD_LALT     => 0x0100,
	KMOD_RALT     => 0x0200,
	KMOD_LMETA    => 0x0400,
	KMOD_RMETA    => 0x0800,
	KMOD_NUM      => 0x1000,
	KMOD_CAPS     => 0x2000,
	KMOD_MODE     => 0x4000,
	KMOD_RESERVED => 0x8000
}; # keymod

use constant{
	KMOD_CTRL	=> (KMOD_LCTRL|KMOD_RCTRL),
	KMOD_SHIFT	=> (KMOD_LSHIFT|KMOD_RSHIFT),
	KMOD_ALT	=> (KMOD_LALT|KMOD_RALT),
	KMOD_META	=> (KMOD_LMETA|KMOD_RMETA),
}; # keymod

# add all the other ":class" tags to the ":all" class,
# deleting duplicates
my %seen;
push @{$EXPORT_TAGS{all}},
grep {!$seen{$_}++} @{$EXPORT_TAGS{$_}} foreach keys %EXPORT_TAGS;

1;
