/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2002 from the
 * contents of Rect.xs. Do not edit this file, edit Rect.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "./Rect.xs"
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#ifndef aTHX_
#define aTHX_
#endif

#include <SDL.h>



#line 23 "./Rect.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

#line 66 "./Rect.c"

XS(XS_Rect_NewRect); /* prototype to pass -Wmissing-prototypes */
XS(XS_Rect_NewRect)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 4)
       croak_xs_usage(cv,  "x, y, w, h");
    {
	Sint16	x = (Sint16)SvIV(ST(0));
	Sint16	y = (Sint16)SvIV(ST(1));
	Uint16	w = (Uint16)SvUV(ST(2));
	Uint16	h = (Uint16)SvUV(ST(3));
	SDL_Rect *	RETVAL;
#line 23 "./Rect.xs"
		RETVAL = (SDL_Rect *) safemalloc (sizeof(SDL_Rect));
		RETVAL->x = x;
		RETVAL->y = y;
		RETVAL->w = w;
		RETVAL->h = h;
#line 90 "./Rect.c"
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), "SDL_RectPtr", (void*)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Rect_RectX); /* prototype to pass -Wmissing-prototypes */
XS(XS_Rect_RectX)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 1)
       croak_xs_usage(cv,  "rect, ...");
    {
	SDL_Rect *	rect;
	Sint16	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "SDL_RectPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    rect = INT2PTR(SDL_Rect *,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"Rect::RectX",
			"rect", "SDL_RectPtr");
#line 35 "./Rect.xs"
		if (items > 1 ) rect->x = SvIV(ST(1)); 
		RETVAL = rect->x;
#line 124 "./Rect.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Rect_RectY); /* prototype to pass -Wmissing-prototypes */
XS(XS_Rect_RectY)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 1)
       croak_xs_usage(cv,  "rect, ...");
    {
	SDL_Rect *	rect;
	Sint16	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "SDL_RectPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    rect = INT2PTR(SDL_Rect *,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"Rect::RectY",
			"rect", "SDL_RectPtr");
#line 44 "./Rect.xs"
		if (items > 1 ) rect->y = SvIV(ST(1)); 
		RETVAL = rect->y;
#line 157 "./Rect.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Rect_RectW); /* prototype to pass -Wmissing-prototypes */
XS(XS_Rect_RectW)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 1)
       croak_xs_usage(cv,  "rect, ...");
    {
	SDL_Rect *	rect;
	Uint16	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "SDL_RectPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    rect = INT2PTR(SDL_Rect *,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"Rect::RectW",
			"rect", "SDL_RectPtr");
#line 53 "./Rect.xs"
		if (items > 1 ) rect->w = SvIV(ST(1)); 
		RETVAL = rect->w;
#line 190 "./Rect.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Rect_RectH); /* prototype to pass -Wmissing-prototypes */
XS(XS_Rect_RectH)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 1)
       croak_xs_usage(cv,  "rect, ...");
    {
	SDL_Rect *	rect;
	Uint16	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "SDL_RectPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    rect = INT2PTR(SDL_Rect *,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"Rect::RectH",
			"rect", "SDL_RectPtr");
#line 62 "./Rect.xs"
		if (items > 1 ) rect->h = SvIV(ST(1)); 
		RETVAL = rect->h;
#line 223 "./Rect.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SDL_RectPtr_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL_RectPtr_DESTROY)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "rect");
    {
	SDL_Rect *	rect;

	if (SvROK(ST(0))) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    rect = INT2PTR(SDL_Rect *,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not a reference",
			"SDL_RectPtr::DESTROY",
			"rect");
#line 73 "./Rect.xs"
	 	printf("RectPtr::DESTROY\n");
		safefree( rect );
#line 254 "./Rect.c"
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Rect); /* prototype to pass -Wmissing-prototypes */
XS(boot_Rect)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    const char* file = __FILE__;

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        newXS("Rect::NewRect", XS_Rect_NewRect, file);
        newXS("Rect::RectX", XS_Rect_RectX, file);
        newXS("Rect::RectY", XS_Rect_RectY, file);
        newXS("Rect::RectW", XS_Rect_RectW, file);
        newXS("Rect::RectH", XS_Rect_RectH, file);
        newXS("SDL_RectPtr::DESTROY", XS_SDL_RectPtr_DESTROY, file);
    if (PL_unitcheckav)
         call_list(PL_scopestack_ix, PL_unitcheckav);
    XSRETURN_YES;
}

