/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2205 from the
 * contents of Timer.xs. Do not edit this file, edit Timer.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "lib/SDLx/Controller/Timer.xs"
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"
#include "ppport.h"

#ifndef aTHX_
#define aTHX_
#endif

#include <SDL.h>
#include "SDLx/Timer.h"

#line 23 "lib\\SDLx\\Controller\\Timer.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 75 "lib\\SDLx\\Controller\\Timer.c"

XS(XS_SDLx__Controller__Timer_new); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDLx__Controller__Timer_new)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 1)
       croak_xs_usage(cv,  "CLASS, ...");
    {
	char*	CLASS = (char *)SvPV_nolen(ST(0));
	sdlx_timer *	RETVAL;
#line 19 "lib/SDLx/Controller/Timer.xs"
		RETVAL = (sdlx_timer *)safemalloc( sizeof(sdlx_timer) );
		RETVAL->started_ticks = 0;
		RETVAL->paused_ticks  = 0;
		RETVAL->started       = 0;
		RETVAL->paused        = 0;
#line 96 "lib\\SDLx\\Controller\\Timer.c"
	ST(0) = sv_newmortal();
        if (RETVAL) {
          void** pointers = malloc(2 * sizeof(void*));
          pointers[0] = (void*)RETVAL;
          pointers[1] = (void*)PERL_GET_CONTEXT;
  	  sv_setref_pv( ST(0), CLASS, (void*)pointers );
        } else {
          XSRETURN_UNDEF;
        }

    }
    XSRETURN(1);
}


XS(XS_SDLx__Controller__Timer_started_ticks); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDLx__Controller__Timer_started_ticks)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 1)
       croak_xs_usage(cv,  "timer, ...");
    {
	sdlx_timer *	timer;
	int	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
           void** pointers = (void**)(SvIV((SV*)SvRV( ST(0) ))); 
           timer = (sdlx_timer *)(pointers[0]);
        } else if (ST(0) == 0) {
           XSRETURN(0);
        } else {
           XSRETURN_UNDEF;
        };
#line 32 "lib/SDLx/Controller/Timer.xs"
		if (items > 1 ) timer->started_ticks = SvIV(ST(1)); 
		RETVAL = timer->started_ticks;
#line 138 "lib\\SDLx\\Controller\\Timer.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SDLx__Controller__Timer_paused_ticks); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDLx__Controller__Timer_paused_ticks)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 1)
       croak_xs_usage(cv,  "timer, ...");
    {
	sdlx_timer *	timer;
	int	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
           void** pointers = (void**)(SvIV((SV*)SvRV( ST(0) ))); 
           timer = (sdlx_timer *)(pointers[0]);
        } else if (ST(0) == 0) {
           XSRETURN(0);
        } else {
           XSRETURN_UNDEF;
        };
#line 41 "lib/SDLx/Controller/Timer.xs"
		if (items > 1 ) timer->paused_ticks = SvIV(ST(1)); 
		RETVAL = timer->paused_ticks;
#line 171 "lib\\SDLx\\Controller\\Timer.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SDLx__Controller__Timer_started); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDLx__Controller__Timer_started)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 1)
       croak_xs_usage(cv,  "timer, ...");
    {
	sdlx_timer *	timer;
	int	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
           void** pointers = (void**)(SvIV((SV*)SvRV( ST(0) ))); 
           timer = (sdlx_timer *)(pointers[0]);
        } else if (ST(0) == 0) {
           XSRETURN(0);
        } else {
           XSRETURN_UNDEF;
        };
#line 50 "lib/SDLx/Controller/Timer.xs"
		if (items > 1 ) timer->started = SvIV(ST(1)); 
		RETVAL = timer->started;
#line 204 "lib\\SDLx\\Controller\\Timer.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SDLx__Controller__Timer_paused); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDLx__Controller__Timer_paused)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 1)
       croak_xs_usage(cv,  "timer, ...");
    {
	sdlx_timer *	timer;
	int	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
           void** pointers = (void**)(SvIV((SV*)SvRV( ST(0) ))); 
           timer = (sdlx_timer *)(pointers[0]);
        } else if (ST(0) == 0) {
           XSRETURN(0);
        } else {
           XSRETURN_UNDEF;
        };
#line 59 "lib/SDLx/Controller/Timer.xs"
		if (items > 1 ) timer->paused = SvIV(ST(1)); 
		RETVAL = timer->paused;
#line 237 "lib\\SDLx\\Controller\\Timer.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SDLx__Controller__Timer_start); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDLx__Controller__Timer_start)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "timer");
    {
	sdlx_timer *	timer;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
           void** pointers = (void**)(SvIV((SV*)SvRV( ST(0) ))); 
           timer = (sdlx_timer *)(pointers[0]);
        } else if (ST(0) == 0) {
           XSRETURN(0);
        } else {
           XSRETURN_UNDEF;
        };
#line 68 "lib/SDLx/Controller/Timer.xs"
		timer->started = 1;
		timer->started_ticks = SDL_GetTicks();
#line 268 "lib\\SDLx\\Controller\\Timer.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_SDLx__Controller__Timer_stop); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDLx__Controller__Timer_stop)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "timer");
    {
	sdlx_timer *	timer;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
           void** pointers = (void**)(SvIV((SV*)SvRV( ST(0) ))); 
           timer = (sdlx_timer *)(pointers[0]);
        } else if (ST(0) == 0) {
           XSRETURN(0);
        } else {
           XSRETURN_UNDEF;
        };
#line 75 "lib/SDLx/Controller/Timer.xs"
		timer->started = 0;
		timer->paused = 0;
#line 298 "lib\\SDLx\\Controller\\Timer.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_SDLx__Controller__Timer_pause); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDLx__Controller__Timer_pause)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "timer");
    {
	sdlx_timer *	timer;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
           void** pointers = (void**)(SvIV((SV*)SvRV( ST(0) ))); 
           timer = (sdlx_timer *)(pointers[0]);
        } else if (ST(0) == 0) {
           XSRETURN(0);
        } else {
           XSRETURN_UNDEF;
        };
#line 82 "lib/SDLx/Controller/Timer.xs"
		if( timer->started == 1 && timer->paused == 0)
		{
			timer->paused = 1;
			timer->paused_ticks = SDL_GetTicks() - timer->started_ticks;
		}
#line 331 "lib\\SDLx\\Controller\\Timer.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_SDLx__Controller__Timer_unpause); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDLx__Controller__Timer_unpause)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "timer");
    {
	sdlx_timer *	timer;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
           void** pointers = (void**)(SvIV((SV*)SvRV( ST(0) ))); 
           timer = (sdlx_timer *)(pointers[0]);
        } else if (ST(0) == 0) {
           XSRETURN(0);
        } else {
           XSRETURN_UNDEF;
        };
#line 92 "lib/SDLx/Controller/Timer.xs"
		timer->paused = 0;
		timer->started_ticks = SDL_GetTicks() - timer->started_ticks;
		timer->paused_ticks = 0;
#line 362 "lib\\SDLx\\Controller\\Timer.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_SDLx__Controller__Timer_get_ticks); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDLx__Controller__Timer_get_ticks)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "timer");
    {
	sdlx_timer *	timer;
	int	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
           void** pointers = (void**)(SvIV((SV*)SvRV( ST(0) ))); 
           timer = (sdlx_timer *)(pointers[0]);
        } else if (ST(0) == 0) {
           XSRETURN(0);
        } else {
           XSRETURN_UNDEF;
        };
#line 100 "lib/SDLx/Controller/Timer.xs"
		if(timer->started == 1)
		{
		   if(timer->paused == 1)
		   {
			RETVAL = timer->paused_ticks;
		   }
		   else
		   {
			int update = SDL_GetTicks();
			int diff = update - timer->started_ticks;
			timer->started_ticks = update;
			RETVAL = diff;
		   }
		}
		else
		{
			RETVAL = 0;
		}
#line 410 "lib\\SDLx\\Controller\\Timer.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SDLx__Controller__Timer_is_started); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDLx__Controller__Timer_is_started)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "timer");
    {
	sdlx_timer *	timer;
	int	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
           void** pointers = (void**)(SvIV((SV*)SvRV( ST(0) ))); 
           timer = (sdlx_timer *)(pointers[0]);
        } else if (ST(0) == 0) {
           XSRETURN(0);
        } else {
           XSRETURN_UNDEF;
        };
#line 126 "lib/SDLx/Controller/Timer.xs"
		RETVAL = timer->started;
#line 442 "lib\\SDLx\\Controller\\Timer.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SDLx__Controller__Timer_is_paused); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDLx__Controller__Timer_is_paused)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "timer");
    {
	sdlx_timer *	timer;
	int	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
           void** pointers = (void**)(SvIV((SV*)SvRV( ST(0) ))); 
           timer = (sdlx_timer *)(pointers[0]);
        } else if (ST(0) == 0) {
           XSRETURN(0);
        } else {
           XSRETURN_UNDEF;
        };
#line 134 "lib/SDLx/Controller/Timer.xs"
		RETVAL = timer->paused;
#line 474 "lib\\SDLx\\Controller\\Timer.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SDLx__Controller__Timer_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDLx__Controller__Timer_DESTROY)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "bag");
    {
	SV *	bag = ST(0);
#line 143 "lib/SDLx/Controller/Timer.xs"
		if( sv_isobject(bag) && (SvTYPE(SvRV(bag)) == SVt_PVMG) ) {
			   void** pointers = (void**)(SvIV((SV*)SvRV( bag ))); 
			   sdlx_timer * timer = (sdlx_timer*)(pointers[0]);
			   if (PERL_GET_CONTEXT == pointers[1]) {
			       pointers[0] = NULL;
			       safefree( pointers );

			       safefree(timer);
			   }
		       } else if (bag == 0) {
			   XSRETURN(0);
		       } else {
			   XSRETURN_UNDEF;
		       }
#line 508 "lib\\SDLx\\Controller\\Timer.c"
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_SDLx__Controller__Timer); /* prototype to pass -Wmissing-prototypes */
XS(boot_SDLx__Controller__Timer)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        newXS("SDLx::Controller::Timer::new", XS_SDLx__Controller__Timer_new, file);
        newXS("SDLx::Controller::Timer::started_ticks", XS_SDLx__Controller__Timer_started_ticks, file);
        newXS("SDLx::Controller::Timer::paused_ticks", XS_SDLx__Controller__Timer_paused_ticks, file);
        newXS("SDLx::Controller::Timer::started", XS_SDLx__Controller__Timer_started, file);
        newXS("SDLx::Controller::Timer::paused", XS_SDLx__Controller__Timer_paused, file);
        newXS("SDLx::Controller::Timer::start", XS_SDLx__Controller__Timer_start, file);
        newXS("SDLx::Controller::Timer::stop", XS_SDLx__Controller__Timer_stop, file);
        newXS("SDLx::Controller::Timer::pause", XS_SDLx__Controller__Timer_pause, file);
        newXS("SDLx::Controller::Timer::unpause", XS_SDLx__Controller__Timer_unpause, file);
        newXS("SDLx::Controller::Timer::get_ticks", XS_SDLx__Controller__Timer_get_ticks, file);
        newXS("SDLx::Controller::Timer::is_started", XS_SDLx__Controller__Timer_is_started, file);
        newXS("SDLx::Controller::Timer::is_paused", XS_SDLx__Controller__Timer_is_paused, file);
        newXS("SDLx::Controller::Timer::DESTROY", XS_SDLx__Controller__Timer_DESTROY, file);

    /* Initialisation Section */

#if XSubPPtmpAAAA
#if XSubPPtmpAAAB
#endif
#if XSubPPtmpAAAC
#endif
#if XSubPPtmpAAAD
#endif
#if XSubPPtmpAAAE
#endif
#if XSubPPtmpAAAF
#endif
#if XSubPPtmpAAAG
#endif
#endif
#if XSubPPtmpAAAA
#if XSubPPtmpAAAB
#endif
#if XSubPPtmpAAAC
#endif
#if XSubPPtmpAAAD
#endif
#endif
#if XSubPPtmpAAAA
#endif
#if XSubPPtmpAAAB
#endif
#if XSubPPtmpAAAC
#endif
#line 578 "lib\\SDLx\\Controller\\Timer.c"

    /* End of Initialisation Section */

#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

